config/routes.rb
Rails.application.routes.draw do
  get "/", to: "main#index", as: "top"
  resources :posts

  namespace :api do
    resources :current_users, default: { format: :json }, only: :show
    resources :users
    resources :posts, default: { format: :json }
    resources :templates, default: { format: :json }
    resources :tree_posts, default: { format: :json }, only: :index
  end

  resources :users, only: [:index, :show, :edit, :update]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    get "/", to: "users#index"
    resources :users do
      resources :admin_users, only: [:create, :destroy]
    
    end
    resource :session
  end

  # angular 関連 いずれ消したい

  get "/service/posts.html", to: "service#posts"
  get "/service/post.html", to: "service#post"
  get "/service/posts/post_view.html", to: "service#post_view"
  get "/service/main.html", to: "service#main"
  get "/service/tree.html", to: "service#tree"
  get "/service/templates.html", to: "service#templates"
  get "/service/template.html", to: "service#template"

  get "/service/posts/show.html", to: "service#post_show"
  get "/service/posts/new.html", to: "service#post_new"

  # get "/posts", to: "service#posts"
  # get "/posts/:id", to: "service#posts"
  # get "/posts/new", to: "service#post"
  # get "/posts/:id/edit", to: "service#post"
  get "/templates", to: "service#templates"
  get "/templates/new", to: "service#template"
  get "/templates/:id", to: "service#template"
end

app/views/share/_post_preview.html.slim
.post-view
  h4.path
    a[ng-href="posts?q%5Bpath_cont={{dir}}" ng-repeat="dir in post_path_split track by $index"]
      |  /{{dir}}
  h1.title
    a.click.click-show[ng-href="/posts/{{post.id}}"]
      |  {{post.path.split("/")[post.path.split("/").length -1]}}
    span[ng-show="post"]
      a.click.click-edit[ng-href="/posts/{{post.id}}/edit"]
        i.fa.fa-pencil
  .post-data
    span.updated_at
      |  {{post.to_json_updated_at}}
    span.updated_user.is-right
      |  {{post.updated_user.name}}
  .post-body#preview[ng-bind-html="previewHtml"]

app/views/share/_posts_list.html.slim
.row[ng-controller="PostsCtrl" ng-init="init()"]
  .col-md-4
    .post-list
      table.table.table-hover.table-posts
        tr
          th.posts
            | Posts
        - @posts.each do |post|
          tr
            td
              span.path
                - post.path.split("/").each do |category|
                  = link_to "/#{category}", posts_path( q:{path_cont: category})
              h3
                a.title[ng-click="preview(#{post.id})"]
                  = post.path.split("/").last
                span
                  = link_to edit_post_path(post), class: "click click-edit" do
                    i.fa.fa-pencil.fa-lg
                  = link_to post, class: "click click-destroy", method: :delete do
                    i.fa.fa-trash.fa-lg
              - post.tags.each do |tag|
                div
                  a.css-tag
                    span
                      = tag.name
                p.updated_user_name
                  = post.updated_user.name

app/views/share/_side.html.slim
.sidebar
  nav.nav-sidebar
    ul.nav
      li[class="#{sidebar_activete :new_post}"]
        a[ng-href="/posts/new"]
          i.fa.fa-pencil.fa-3x
          p
            |  New Post
      li[class="#{sidebar_activete :main}"]
        a[ng-href="/"]
          i.fa.fa-home.fa-3x
          p
            |  HOME
      li[class="#{sidebar_activete :posts}"]
        a[href="/posts"]
          i.fa.fa-file-text-o.fa-3x
          p
            |  Posts
      li[class="#{sidebar_activete :template}"]
        a[href="/templates"]
          i.fa.fa-file-code-o.fa-3x
          p
            | Templates
      li[class="#{sidebar_activete :tag}"]
        a[href=""]
          i.fa.fa-tags.fa-3x
          p
            |  Tags
      li[class="#{sidebar_activete :logout}"]
        = link_to session_path, method: :delete do
          i.fa.fa-sign-out.fa-3x
          p
            | Logout