config/routes.rb
Rails.application.routes.draw do
  get "/", to: "main#index", as: "top"
  resources :posts

  namespace :api do
    resources :current_users, default: { format: :json }, only: :show
    resources :users
    resources :posts, default: { format: :json }
    resources :templates, default: { format: :json }
    resources :tree_posts, default: { format: :json }, only: :index
  end

  resources :users, only: [:index, :show, :edit, :update]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    get "/", to: "users#index"
    resources :users do
      resources :admin_users, only: [:create, :destroy]
    
    end
    resource :session
  end

  # angular 関連 いずれ消したい

  get "/service/posts.html", to: "service#posts"
  get "/service/post.html", to: "service#post"
  get "/service/posts/post_view.html", to: "service#post_view"
  get "/service/main.html", to: "service#main"
  get "/service/tree.html", to: "service#tree"
  get "/service/templates.html", to: "service#templates"
  get "/service/template.html", to: "service#template"

  get "/service/posts/show.html", to: "service#post_show"
  get "/service/posts/new.html", to: "service#post_new"

  # get "/posts", to: "service#posts"
  # get "/posts/:id", to: "service#posts"
  # get "/posts/new", to: "service#post"
  # get "/posts/:id/edit", to: "service#post"
  get "/templates", to: "service#templates"
  get "/templates/new", to: "service#template"
  get "/templates/:id", to: "service#template"
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_paranoid
  include AASM
  include CurrentUser
  include JsonModel

  has_many :post_tags
  has_many :tags, through: :post_tags

  aasm do
    state :new, initial: true
    state :wip
    state :saved
    state :editing

    event :wip_save do
      transitions from: :new, to: :wip
    end
  end

  before_create :wip_save

  paginates_per 10

  def self.tree
    root_tree = TreePost.new
    all.each do |post|
      root_tree.insert_post post.path.split('/'), post
    end
    root_tree
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :set_post, only: [:update, :show, :destroy]
  protect_from_forgery except: [:create, :update, :destroy]
  def index
    if params[:q].present?
      search = Post.search(params[:q])
      @posts = search.result
    else
      @posts = Post.all
    end
    @posts = @posts.order(updated_at: :desc)
    render json: @posts.to_json(
      include: [
        :tags,
        {created_user: {except: :password_digest}},
        {updated_user: {except: :password_digest}},
      ],
        methods: [
          :to_json_created_at,
          :to_json_updated_at
      ]
    )
  end

  def show
    render json: @post.to_json(include: [:tags, updated_user: {except: :password_digest}])
  end

  def new

  end

  def create
    post = Post.create(post_params)
    render json: post, status: 201
  end

  def edit

  end

  def update
    @post.update(post_params)
    render json: @post, status: 201
  end

  def destroy
    @post.destroy
    render nothing: true, status: 204
  end

  private
  def set_post
    @post = Post.find params[:id]
  end

  def post_params
    params.require(:post).permit(
      :id, :path, :body,
      :_destroy,
      :created_user_id, :updated_user_id,
       :deleted_at,
    )
  end

end

app/controllers/posts_controller.rb
require 'html/pipeline'
class PostsController < ApplicationController
  before_action :set_post, only: [:destroy, :show]
  def index
    @search = Post.search(params[:q])
    @posts = @search.result.page(params[:page])
    @posts = @posts.order(updated_at: :desc).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def show
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
    end
  end

  private

  def set_post
    @post = Post.find params[:id]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
.row[ng-controller="PostCtrl" ng-init="init()"]
  .alert.alert-success[role="alert" ng-show="saved"]
    | Well done! You
    strong
      |  successfully Posts!
  .col-md-6.col-sm-5.editer.post-editer
    form.post-form
      .form-group
        .form-header
          h3
            | 投稿編集
          select#selectbasic.form-control[name="selectbasic" ng-model="selectedTemplate" ng-options="template.path_set_date for template in templates" ng-change="selectTemplate()"]

          input#path.form-control[type="text" placeholder="Title" ng-model="post.path" ng-change="changePath(post.path)"]
        textarea#textarea.form-control.body-area.tabIndent[name="textarea" ng-model="post.body" ng-change="changeBody()" placeholder="本文"]

        .form-inline
          .tag-list.is-float-left[ng-repeat="tag in post.tags"]
            a.css-tag.form[ng-click="destroyTag(tag)"]
              span
                | {{tag.name}}
          input#tag[type="text" placeholder="Tag" ng-model="addedTag" ng-keydown="addTag($event)"]
        .form-bottom
          .btn-group
            button.btn.btn-success[ng-click="wipPost(post)"]
              | Save Post
  .col-md-6.col-sm-7
    .post-view
      h4.path
        a[ng-href="/" ng-repeat="dir in post_path_split track by $index"]
          |  /{{dir}}
      h1.title
        a.click.click-show[ng-href="/posts/{{post.id}}"]
          |  {{post.path.split("/")[post.path.split("/").length -1]}}
      .post-data
        span.updated_at
          |  {{post.to_json_updated_at}}
        span.updated_user.is-right
          |  {{post.updated_user.name}}
      .post-body[ng-bind-html="previewHtml"]

app/views/posts/_post_preview.html.slim
.post-view
  h4.path
    a[ng-href="/" ng-repeat="dir in post_path_split()"]
      |  /{{dir}}
  h1.title
    a.click.click-show[ng-href="/posts/{{post.id}}"]
      |  {{post.path.split("/")[post.path.split("/").length -1]}}
    span[ng-show="post"]
      a.click.click-edit[ng-href="/posts/{{post.id}}/edit"]
        i.fa.fa-pencil.fa-lg
  .post-data
    span.updated_at
      |  {{post.to_json_updated_at}}
    span.updated_user.is-right
      |  {{post.updated_user.name}}
  .post-body#preview[ng-bind-html="previewHtml"]

app/views/posts/edit.html.slim
== render "form"

app/views/posts/index.html.slim
.row[ng-controller="PostsCtrl" ng-init="init()"]
  / Post 検索用フォーム
  .col-md-4
    = search_form_for @search, class: "post-form" do |f|
      .input-group
        span.input-group-addon
          i.fa.fa-search
        = f.text_field :path_start, class: "form-control", placeholder: "Search for path"
      .input-group
        span.input-group-addon
          i.fa.fa-user
        = f.text_field :updated_user_name_cont, class: "form-control", placeholder: "Search for user"
      .input-group
        span.input-group-addon
          i.fa.fa-file-text-o
        = f.text_field :body_cont, class: "form-control", placeholder: "Search for content"
      .action-button
        = button_tag type: :submit, class: "btn btn-primary" do
          i.fa.fa-search
    .post-list
      table.table.table-hover.table-posts
        tr
          th.posts
            | Posts

        = paginate @posts, window: 4 

        - @posts.each do |post|
          tr
            td
              span.path
                - post.path.split("/").each do |category|
                  = link_to "/#{category}", posts_path(q:{path_cont: category})
              h3
                a.title[ng-click="preview(#{post.id})"]
                  = link_to post.path.split("/").last, post_path(post.id)
                span
                  = link_to edit_post_path(post), class: "click click-edit" do
                    i.fa.fa-pencil.fa-lg
                  = link_to post, class: "click click-destroy", method: :delete do
                    i.fa.fa-trash.fa-lg
              - post.tags.each do |tag|
                div
                  a.css-tag
                    span
                      = tag.name
              p.updated_user_name
                = post.updated_user.name

  

app/views/posts/new.html.slim
== render "form"

app/views/posts/show.html.slim
.post-view
  h4.path
    - @post.path.split("/").each do |category|
      = link_to "/#{category}", posts_path( q:{path_cont: category})
  h1.title
    = @post.path.split("/").last
    span
      = link_to edit_post_path(@post), class: "click click-edit" do
        i.fa.fa-pencil.fa-lg
  .post-data
    span.updated_at
      = @post.updated_at
    span.updated_user.is-right
      = @post.updated_user.name
  .post-body#preview
    / TODO マークダウンコンパイラ統一したい ruby でやるか js でやるか
    = html_pipeline(@post.body).html_safe