config/routes.rb
Rails.application.routes.draw do
  get "/", to: "main#index", as: "top"
  resources :posts

  namespace :api do
    resources :current_users, default: { format: :json }, only: :show
    resources :users
    resources :posts, default: { format: :json }
    resources :templates, default: { format: :json }
    resources :tree_posts, default: { format: :json }, only: :index
  end

  resources :users, only: [:index, :show, :edit, :update]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    get "/", to: "users#index"
    resources :users do
      resources :admin_users, only: [:create, :destroy]
    
    end
    resource :session
  end

  # angular 関連 いずれ消したい

  get "/service/posts.html", to: "service#posts"
  get "/service/post.html", to: "service#post"
  get "/service/posts/post_view.html", to: "service#post_view"
  get "/service/main.html", to: "service#main"
  get "/service/tree.html", to: "service#tree"
  get "/service/templates.html", to: "service#templates"
  get "/service/template.html", to: "service#template"

  get "/service/posts/show.html", to: "service#post_show"
  get "/service/posts/new.html", to: "service#post_new"

  # get "/posts", to: "service#posts"
  # get "/posts/:id", to: "service#posts"
  # get "/posts/new", to: "service#post"
  # get "/posts/:id/edit", to: "service#post"
  get "/templates", to: "service#templates"
  get "/templates/new", to: "service#template"
  get "/templates/:id", to: "service#template"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :email_or_name
  acts_as_paranoid
  before_save { self.email = email.downcase }
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  #update のときは認証なしに変更可能に
  validates :password, length: { minimum: 6 }, on: :create
  validates :password, length: { minimum: 6 }, on: :update, allow_blank: true
  validates :joinyear, :role, :status, presence: :true
  has_secure_password

  has_one :admin_user

  enum role: { professor: 1, assistant_professor: 2, master: 3, bachelor: 4 }
  enum status: { enrolled: 1, graduation: 2 }

  def self.email?(string)
    string =~ VALID_EMAIL_REGEX
  end

  # current_user_id にすべき
  def self.current_user=(user)
    Thread.current[:user_id] = user.id
  end

  def self.current_user
    User.find_by id: Thread.current[:user_id]
  end

  def self.reset_current_user
    Thread.current[:user_id] = nil
  end

  def admin?
    admin_user.present?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    if user_params[:password] == params[:user][:password_agein]
      @user = User.new user_params
      if @user.save
        redirect_to admin_users_path
      else
        render :new
      end
    else
      @user = User.new user_params
      render :new
    end
  end

  def edit
  end

  def show 
  end

  def update
    if @user.update user_params 
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :joinyear,
      :role,
      :status,
      :description
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]

  def show
    render json: @user
  end

  # def new
  #   @user = User.new
  # end
  #
  # def create
  #   get_params = user_params
  #   if get_params[:password] == get_params[:password_agein]
  #     get_params.delete :password_agein
  #     @user = User.new(get_params)
  #     if @user.save
  #       redirect_to new_sessions_path(create_user: :success) and return
  #     else
  #       render :new
  #     end
  #   else
  #     get_params.delete :password_agein
  #     @user = User.new(get_params)
  #     render :new
  #   end
  # end

  private

  def user_params
    params.require(:user).permit(
      :id, :name, :email, :password, :password_agein
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.slim
= bootstrap_form_for [:admin, user] do |f|
  .form-group
    = f.text_field :name
  .form-group.field
    = f.text_field :email
  .form-group
    = f.password_field :password
  .form-group
    = f.password_field :password_agein
  hr
  .form-group
    = f.number_field :joinyear
  .form-group
    = f.select :status, User.statuses_i18n.to_a.map(&:reverse!)
  .form-group
    = f.select :role, User.roles_i18n.to_a.map(&:reverse!)
  = f.submit class: "btn btn-primary"

app/views/admin/users/edit.html.slim
h1 編集処理 
= bootstrap_form_for [:admin, @user] do |f|
  hr.form-group
  = f.text_field :name
  = f.email_field :email
  = f.password_field :password
  = f.password_field :password_again
  hr.form-group
  = f.number_field :joinyear
  = f.select :status, User.statuses_i18n.to_a.map(&:reverse!)
  = f.select :role, User.roles_i18n.to_a.map(&:reverse!)
  = f.submit "登録する", class: "btn btn-primary"
  = link_to "戻る", admin_users_path, class: "btn btn-default"

app/views/admin/users/index.html.slim
h1 ユーザ一覧

= link_to "新規作成", new_admin_user_path, class: "btn btn-primary"


table.table
  tr
    th ユーザネーム
    th アドレス
    th 年度
    th 役職
    th 状態
    th
  - @users.each do |user|
    tr
      td = user.name
      td = user.email
      td = user.joinyear
      td = user.role_i18n
      td = user.status_i18n
      td = user.admin? ? "管理者" : link_to("管理者権限を付与", admin_user_admin_users_path(user), method: :post, class: "btn btn-warning", data: { confirm:  "#{user.name} に管理者権限を付与してもよろしいですか?" })
      td = user.admin? ? link_to("管理者権限を剥奪", admin_user_admin_user_path(user,user.admin_user), method: :delete, class: "btn btn-warning", data: { confirm:  "#{user.name} の管理者権限を剥奪してもよろしいですか?" }) : "管理者"
      td = link_to "編集", edit_admin_user_path(user), class: "btn btn-info"
      td = link_to "削除", admin_user_path(user), method: :delete, class: "btn btn-danger", data: { confirm:  "#{user.name} を削除してもよろしいですか?" }

app/views/admin/users/new.html.slim
- if @user.errors.present?
  .alert.alert-danger role="alert"
    - @user.errors.full_messages.each do |message|
      p = message
h1 ユーザ新規作成
== render "form", user: @user
= link_to "戻る", admin_users_path, class: "btn btn-default"